language: node_js
node_js:
  - '9'
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn build --base-href https://chrisxjh.github.io/uw-course-explorer/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/uw-course-explorer
  on:
    branch: master
